---

- name: install prometheus
  shell: wget https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz;tar -xvf prometheus-2.39.1.linux-amd64.tar.gz
  become: true

- name: move prometheus
  shell: cd prometheus-2.39.1.linux-amd64; sudo mv prometheus promtool /usr/local/bin/;sudo mv consoles/console_libraries/ /etc/prometheus/;sudo mv prometheus.yml /etc/prometheus/prometheus.yml

- name: set correct ownership
  shell: sudo chown -R prometheus:prometheus /etc/prometheus /data/

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
